/* Public portfolio content only. Keep private findings and identifiers out of this file. */
'use strict';
window.KOS_CONTENT = {
  email: 'yaswanthkukkala123@gmail.com',
  linkedin: 'https://www.linkedin.com/in/yaswanth-kalendra-kukkala-37b7701a0/',
  github: 'https://github.com/kalendra456',
  apps: [
    { id: 'home', name: 'Overview', subtitle: 'Start here', icon: 'home', color: 'mint' },
    { id: 'profile', name: 'Profile', subtitle: 'Experience & credentials', icon: 'user', color: 'blue' },
    { id: 'surface', name: 'Attack Surface', subtitle: 'Assessment domains', icon: 'scan', color: 'mint' },
    { id: 'findings', name: 'Findings Vault', subtitle: 'Sanitized research', icon: 'vault', color: 'amber' },
    { id: 'methodology', name: 'Methodology', subtitle: 'Scope to verified closure', icon: 'workflow', color: 'violet' },
    { id: 'recognition', name: 'Recognition', subtitle: 'Public acknowledgments', icon: 'award', color: 'amber' },
    { id: 'operations', name: 'Operations', subtitle: 'Defensive engineering', icon: 'activity', color: 'blue' },
    { id: 'files', name: 'Case Files', subtitle: 'Technical documentation', icon: 'folder', color: 'mint' },
    { id: 'terminal', name: 'Terminal', subtitle: 'Explore by command', icon: 'terminal', color: 'neutral' },
    { id: 'contact', name: 'Contact', subtitle: 'Start a conversation', icon: 'mail', color: 'violet' }
  ],
  domains: [
    {name:'Web Application Security',label:'Web applications',focus:'Beyond the scanner.',description:'Manual assessment of authentication, sessions, file handling, injection and high-value business workflows. The focus is on realistic exploitability and the controls that should prevent abuse.',checks:['Authentication and session lifecycle','Input handling and file-upload controls','Business workflows and trust decisions'],outcome:'Reproducible evidence, root cause, business consequence and practical remediation.',tags:['Web Pentesting','Burp Suite','DAST','Manual Validation']},
    {name:'API Security & Authorization',label:'APIs & authorization',focus:'Every boundary matters.',description:'Authorization-focused assessment of REST and JSON workflows across users, roles, tenants, objects and state transitions.',checks:['BOLA / IDOR and object ownership','Role, tenant and privilege-boundary matrices','Multi-step business-logic validation'],outcome:'A clear account of which identity can perform which action on which resource.',tags:['API Security','BOLA / IDOR','Access Control','OAuth / OIDC']},
    {name:'Application Security Validation',label:'Source to runtime',focus:'Prove what the code permits.',description:'Correlate source-code reasoning, SAST signals, DAST behavior and negative controls to distinguish exploitable weaknesses from false positives.',checks:['Source-to-sink and trust-boundary analysis','Root-cause review and scanner triage','Remediation verification and regression checks'],outcome:'Developer-ready findings backed by both code reasoning and observed behavior.',tags:['Code Review','SAST + DAST','Root Cause','Retesting']},
    {name:'Complex Logic & Protocol Security',label:'Logic & protocols',focus:'Understand the system, not just the request.',description:'Source-assisted evaluation of state transitions, cross-system trust, resource constraints and atomic workflows that can affect availability or integrity.',checks:['State machines, invariants and atomic workflows','Cross-system trust and resource boundaries','Availability, integrity and recovery paths'],outcome:'Methodology-level research context. Active private findings and target identifiers are not published here.',tags:['Protocol Logic','State Integrity','Invariant Analysis','Resource Boundaries']},
    {name:'Detection-Informed Engineering',label:'Defensive context',focus:'Findings that defenders can use.',description:'SOC, SIEM/XDR, endpoint telemetry and incident workflows provide operational context for assessing prevention, detection and response.',checks:['SIEM correlation and EDR-visible telemetry','Detection-rule validation and alert tuning','SOAR-aligned incident orchestration'],outcome:'Offensive findings informed by real-world logging, investigation and response constraints.',tags:['SIEM / XDR','EDR Context','Detection Engineering','SOAR-aligned']}
  ],
  stages: [
    {name:'Control scope',short:'Scope',question:'What is authorized, and what does success look like?',body:'Define assets, identities, test windows, constraints, evidence handling, escalation paths and success criteria before testing begins.',items:['Agreed assets and rules of engagement','Test identities and permitted actions','Evidence-handling and escalation plan'],deliverable:'A bounded, prioritized assessment plan.'},
    {name:'Model the attack surface',short:'Model',question:'Where does the system make a trust decision?',body:'Map roles, objects, data flows, trust boundaries and high-value state transitions to form focused test hypotheses.',items:['Roles, objects and tenant boundaries','Data flows and state transitions','Risk-based testing priorities'],deliverable:'A hypothesis-driven coverage matrix.'},
    {name:'Validate exploitability',short:'Validate',question:'Can the hypothesis survive a negative control?',body:'Use manual testing, source-assisted reasoning and controlled proofs of concept to demonstrate realistic attack paths.',items:['Reproducible behavior','Negative controls and preconditions','Bounded, authorized impact validation'],deliverable:'Evidence that separates a weakness from an exploitable finding.'},
    {name:'Calibrate risk',short:'Explain',question:'What changes for the business?',body:'Deduplicate evidence, assess severity, identify root cause and explain consequence to technical and non-technical stakeholders.',items:['Independent severity assessment','Business impact and root cause','Clear, actionable stakeholder reporting'],deliverable:'A risk decision supported by technical evidence.'},
    {name:'Remediate & retest',short:'Close',question:'Does the corrective control actually hold?',body:'Translate findings into corrective controls, validate the fix and test for bypasses or regressions against explicit closure criteria.',items:['Remediation guidance','Bypass and regression checks','Evidence-based closure criteria'],deliverable:'A documented retest outcome, not an assumed fix.'}
  ],
  findings: [
    {id:'identity',category:'case',label:'Sanitized case',title:'Identity & trust-flow control failure',status:'Confirmed critical',description:'A Government Private Program authentication workflow, assessed through identity transitions, trust decisions and negative-control tests.',tags:['Identity','Authentication','Business Logic'],body:'Mapped identity transitions and trust decisions across a complex authentication workflow and demonstrated an exploitable control failure with clear impact evidence. Delivery included a reproducible proof of concept, root-cause analysis and remediation guidance.',note:'One confirmed report received an approximately $10K award. Reward levels are program-specific; the outcome is evidence of validated impact, not a ceiling on research capability.'},
    {id:'authorization',category:'method',label:'Methodology',title:'Authorization boundary validation',status:'Assessment practice',description:'Role, tenant, object and state-transition controls tested through multi-user negative controls.',tags:['API Security','BOLA / IDOR','Access Control'],body:'A structured approach to comparing permitted and denied actions across roles, tenants, objects and workflow states. The emphasis is on ownership checks, trust boundaries and reproducible evidence.',note:'This is a capability summary, not a separately disclosed report or a claim of a specific severity.'},
    {id:'code',category:'method',label:'Methodology',title:'Code-to-runtime validation',status:'Assessment practice',description:'Source paths, configuration and runtime behavior connected to explain exploitability and root cause.',tags:['SAST + DAST','Source Review','Root Cause'],body:'Correlate code paths and trust decisions with observed runtime behavior and negative controls. Use the evidence to reduce false positives and give developers a precise remediation target.',note:'This is a methodology summary. No private source code, exploit details or active report identifiers are included.'},
    {id:'governance',category:'method',label:'Methodology',title:'Finding lifecycle ownership',status:'Delivery practice',description:'Reproduction, deduplication, severity calibration, impact communication and explicit retest criteria.',tags:['Triage','Risk Communication','Remediation'],body:'Treat findings as a controlled delivery workstream: confirm behavior, preserve evidence, calibrate severity, explain risk and agree on remediation and retest criteria.',note:'The workflow illustrates the delivery approach; it is not a live client engagement or incident dashboard.'}
  ],
  proofs: [
    {name:'SAP',kind:'Security Credits',image:'../assets/recognitions/sap-credits.jpg',description:'Public SAP Security Credits recognition associated with responsible security research.'},
    {name:'Accenture',kind:'Responsible Disclosure',image:'../assets/recognitions/accenture-hof.jpg',description:'Public recognition associated with responsible vulnerability disclosure.'},
    {name:'ALDI',kind:'IT Security Hall of Fame',image:'../assets/recognitions/aldi-hof.jpg',description:'Public Hall of Fame evidence associated with responsible disclosure.'},
    {name:'Drexel University',kind:'Hall of Fame',image:'../assets/recognitions/drexel-hof.jpg',description:'Public Hall of Fame recognition following responsible vulnerability disclosure.'}
  ],
  projects: [
    {name:'Wazuh 5 SIEM & Log Pipeline',label:'SIEM / XDR · TELEMETRY',description:'Isolated Wazuh 5 validation, endpoint-agent coverage, ISO 27001 testing and firewall syslog ingestion into an OpenSearch-backed investigation pipeline.',result:'Validated certificates, agent health, Windows/Linux telemetry, connectors, data streams and searchable security events.',tags:['Wazuh 5','OpenSearch','Syslog','Endpoint Telemetry'],flow:['Endpoint / firewall','Wazuh / OpenSearch','Investigation'],href:'../case-studies/#wazuh-iso27001'},
    {name:'Unified SOC Observability',label:'VISIBILITY · INVESTIGATION',description:'Correlated Wazuh and OpenSearch security data with Grafana, Zabbix, SNMP and infrastructure-health signals.',result:'A connected view of endpoint, security, availability and network telemetry for investigation.',tags:['Grafana','Zabbix','SNMP','SIEM Analytics'],flow:['Security signals','Infrastructure health','Unified dashboards'],href:'../case-studies/#unified-soc-dashboard'},
    {name:'Incident Workflow Automation',label:'SOAR-ALIGNED · RESPONSE',description:'Converted selected Wazuh alerts into controlled, deduplicated GLPI incidents with preserved security context.',result:'Improved incident traceability, triage consistency and response ownership while reducing duplicate tickets.',tags:['Wazuh','GLPI','Deduplication','ITSM'],flow:['Wazuh alert','Deduplication','GLPI incident'],href:'../case-studies/#wazuh-glpi'}
  ],
  files: [
    {name:'Wazuh 5 validation lab',category:'SIEM / XDR',description:'Isolated validation environment, endpoint coverage and ISO 27001 testing context.',href:'../case-studies/#wazuh-iso27001'},
    {name:'Firewall syslog integration',category:'LOG ENGINEERING',description:'Network-security event collection and searchable investigation data.',href:'../case-studies/#firewall-syslog'},
    {name:'Unified SOC dashboard',category:'OBSERVABILITY',description:'Wazuh, Grafana and Zabbix in an integrated monitoring workflow.',href:'../case-studies/#unified-soc-dashboard'},
    {name:'Wazuh → GLPI integration',category:'WORKFLOW AUTOMATION',description:'Alert-to-incident orchestration with deduplication and controlled ticket creation.',href:'../case-studies/#wazuh-glpi'}
  ]
};
